name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write        # ← butuh untuk git push

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node (for possible asset pipelines)
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Build # (optional – static site so nothing to build)
        run: echo "Skip build"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # ← ganti ini
          publish_dir: ./  # folder root atau `dist/`

          